### ISSUE TITLE
Null message

### ISSUE THREAD

**Issue by Poea** [polpoy/colyseus-construct-plugin#1]
Whenever I use the ping command it sends a null message in room updates and only shows up on the server, Is this normal or is it not sending the information correctly?

**Comment by lgugl** [comment]
Hum, this is not normal. The ping command seams to works perfectly for me (clean npm install). With Construct 2 build 244, and NodeJS 6.9.4 (same with 7.7.3).
Do you have the null message with Construct and with the html client test file?

**Comment by Keevle** [comment]
@polpoy This happens to me too with Construct![image](http://i.imgur.com/QhpOLPh.png)

When I use the ping command it sends the correct ping to the server's log but it sends null to the room update on construct 2, Do you think this is because I didn't use the server that came with this plugin? Due to their being an Error with Debug

**Comment by Poea** [comment]
Thank you for the fix
